// const HarryPotter = {
//   'Gryffindor': null,
//   'Ravenclaw': null,
//   'Slytherin': null,
//   'Hufflepuff': null,
//   'Durmstrang': null,
//   'Beauxbatons': null,
//   'Team Harry': null,
//   'Team Voldemort': null,
//   'Team Dumbledore': null,
//   'Team Malfoy': null,
//   'Team Hermione': null,
//   'Team Weasley': null,
//   'Team Auror': null,
//   'Azkaban': null,
//   'Mahoutokoro': null,
//   'Uagadou': null,
//   'Koldovstoretz': null,
// };

// const Twilight = {
//   'Team Edward': null,
//   'Team Jacob': null,
//   'Team Bella': null,
//   'Team Tyler': null,
//   'Team Alice': null,
//   'Team Rosalie': null,
//   'Team Jasper': null,
//   'Team Cullen': null,
//   'Team Victoria': null,
//   'Team Swan': null,
//   'Team Laurent': null,
//   'Team Stanley': null,
//   'Team James': null,
//   'Team Newton': null,
//   'Team Yorkie': null,
//   'Team Black': null,
//   'Team Weber': null,
//   'Team Phil': null,
//   'Team Forge': null,
//   'Team Molina': null,
//   'Team Amber': null,  
// };

const Colors = {
  "Team Aero Blue": "#C0E8D5",
  "Team Alice Blue": "#F0F8FF",
  "Team Amaranth Pink": "#F19CBB",
  "Team Amaranth Red": "#D3212D",
  "Team Antique Brass": "#CD9575",
  "Team Antique White": "#FAEBD7",
  "Team Arctic Lime": "#D0FF14",
  "Team Atomic Tangerine": "#FF9966",
  "Team Baby Blue": "#89CFF0",
  "Team Baby Blue Eyes": "#A1CAF1",
  "Team Baby Pink": "#F4C2C2",
  "Team Baby Powder": "#FEFEFA",
  "Team Baker-Miller Pink": "#FF91AF",
  "Team Banana Mania": "#FAE7B5",
  "Team Barbie Pink": "#DA1884",
  "Team Beau Blue": "#BCD4E6",
  "Team Bitter Lemon": "#CAE00D",
  "Team Bitter Lime": "#BFFF00",
  "Team Bleu De France": "#318CE7",
  "Team Blizzard Blue": "#ACE5EE",
  "Team Blue Bell": "#A2A2D0",
  "Team Blue Jeans": "#5DADEC",
  "Team Brick Red": "#CB4154",
  "Team Bright Green": "#66FF00",
  "Team Bright Lilac": "#D891EF",
  "Team Bright Navy Blue": "#1974D2",
  "Team Brilliant Rose": "#FF55A3",
  "Team Brink Pink": "#FB607F",
  "Team Burnt Orange": "#CC5500",
  "Team Burnt Sienna": "#E97451",
  "Team Cadmium Orange": "#ED872D",
  "Team Cadmium Red": "#E30022",
  "Team Cadmium Yellow": "#FFF600",
  "Team Cameo Pink": "#EFBBCC",
  "Team Canary Yellow": "#FFEF00",
  "Team Candy Apple Red": "#FF0800",
  "Team Candy Pink": "#E4717A",
  "Team Caribbean Green": "#00CC99",
  "Team Carnation Pink": "#FFA6C9",
  "Team Carolina Blue": "#56A0D3",
  "Team Carrot Orange": "#ED9121",
  "Team Celtic Blue": "#246BCE",
  "Team CG Red": "#E03C31",
  "Team Champagne Pink": "#F1DDCF",
  "Team Charm Pink": "#E68FAC",
  "Team Cherry Blossom Pink": "#FFB7C5",
  "Team China Pink": "#DE6FA1",
  "Team Chinese Yellow": "#FFB200",
  "Team Chrome Yellow": "#FFA700",
  "Team Cinnamon Satin": "#CD607E",
  "Team Cocoa Brown": "#D2691E",
  "Team Columbia Blue": "#B9D9EB",
  "Team Congo Pink": "#F88379",
  "Team Copper Red": "#CB6D51",
  "Team Coral Pink": "#F88379",
  "Team Cornflower Blue": "#6495ED",
  "Team Cosmic Latte": "#FFF8E7",
  "Team Cotton Candy": "#FFBCD9",
  "Team Cyber Yellow": "#FFD300",
  "Team Dark Orange": "#FF8C00",
  "Team Dark Orchid": "#9932CC",
  "Team Dark Salmon": "#E9967A",
  "Team Dark Sky Blue": "#8CBED6",
  "Team Dark Turquoise": "#00CED1",
  "Team Deep Cerise": "#DA3287",
  "Team Deep Champagne": "#FAD6A5",
  "Team Deep Pink": "#FF1493",
  "Team Deep Saffron": "#FF9933",
  "Team Deep Sky Blue": "#00BFFF",
  "Team Desert Sand": "#EDC9AF",
  "Team Dodger Blue": "#1E90FF",
  "Team Dogwood Rose": "#D71868",
  "Team Dutch White": "#EFDFBB",
  "Team Earth Yellow": "#E1A95F",
  "Team Electric Blue": "#7DF9FF",
  "Team Electric Green": "#00FF00",
  "Team Electric Indigo": "#6F00FF",
  "Team Electric Lime": "#CCFF00",
  "Team Electric Purple": "#BF00FF",
  "Team Electric Violet": "#8F00FF",
  "Team English Vermillion": "#CC474B",
  "Team Fandango Pink": "#DE5285",
  "Team Fiery Rose": "#FF5470",
  "Team Fire Opal": "#E95C4B",
  "Team Floral White": "#FFFAF0",
  "Team Fluorescent Blue": "#15F4EE",
  "Team French Lime": "#9EFD38",
  "Team French Mauve": "#D473D4",
  "Team French Pink": "#FD6C9E",
  "Team French Rose": "#F64A8A",
  "Team French Sky Blue": "#77B5FE",
  "Team Ghost White": "#F8F8FF",
  "Team Golden Poppy": "#FCC200",
  "Team Golden Yellow": "#FFDF00",
  "Team Granny Smith Apple": "#A8E4A0",
  "Team Green Lizard": "#A7F432",
  "Team Han Blue": "#446CCF",
  "Team Han Purple": "#5218FA",
  "Team Hansa Yellow": "#E9D66B",
  "Team Harvest Gold": "#DA9100",
  "Team Heat Wave": "#FF7A00",
  "Team Hollywood Cerise": "#F400A1",
  "Team Hot Magenta": "#FF1DCE",
  "Team Hot Pink": "#FF69B4",
  "Team Imperial Red": "#ED2939",
  "Team Indian Red": "#CD5C5C",
  "Team Indian Yellow": "#E3A857",
  "Team Italian Sky Blue": "#B2FFFF",
  "Team June Bud": "#BDDA57",
  "Team Key Lime": "#E8F48C",
  "Team Languid Lavender": "#D6CADD",
  "Team Laser Lemon": "#FFFF66",
  "Team Lavender Blue": "#CCCCFF",
  "Team Lavender Blush": "#FFF0F5",
  "Team Lavender Gray": "#C4C3D0",
  "Team Lawn Green": "#7CFC00",
  "Team Lemon Chiffon": "#FFFACD",
  "Team Lemon Curry": "#CCA01D",
  "Team Lemon Glacier": "#FDFF00",
  "Team Lemon Meringue": "#F6EABE",
  "Team Light Blue": "#ADD8E6",
  "Team Light Coral": "#F08080",
  "Team Light Cornflower Blue": "#93CCEA",
  "Team Light Cyan": "#E0FFFF",
  "Team Light Goldenrod Yellow": "#FAFAD2",
  "Team Light Gray": "#D3D3D3",
  "Team Light Green": "#90EE90",
  "Team Light Orange": "#FED8B1",
  "Team Light Periwinkle": "#C5CBE1",
  "Team Light Pink": "#FFB6C1",
  "Team Light Salmon": "#FFA07A",
  "Team Light Sky Blue": "#87CEFA",
  "Team Light Steel Blue": "#B0C4DE",
  "Team Light Yellow": "#FFFFE0",
  "Team Lime Green": "#32CD32",
  "Team Liseran Purple": "#DE6FA1",
  "Team Macaroni And Cheese": "#FFBD88",
  "Team Madder Lake": "#CC3336",
  "Team Magic Mint": "#AAF0D1",
  "Team Majorelle Blue": "#6050DC",
  "Team Mango Tango": "#FF8243",
  "Team Maximum Blue": "#47ABCC",
  "Team Maximum Blue Purple": "#ACACE6",
  "Team Maximum Green Yellow": "#D9E650",
  "Team Maximum Red": "#D92121",
  "Team Maximum Yellow": "#FAFA37",
  "Team Maximum Yellow Red": "#F2BA49",
  "Team Maya Blue": "#73C2FB",
  "Team Medium Aquamarine": "#66DDAA",
  "Team Medium Blue": "#0000CD",
  "Team Medium Candy Apple Red": "#E2062C",
  "Team Medium Champagne": "#F3E5AB",
  "Team Medium Orchid": "#BA55D3",
  "Team Medium Purple": "#9370DB",
  "Team Medium Slate Blue": "#7B68EE",
  "Team Medium Spring Green": "#00FA9A",
  "Team Medium Turquoise": "#48D1CC",
  "Team Mellow Apricot": "#F8B878",
  "Team Mellow Yellow": "#F8DE7E",
  "Team Metallic Gold": "#D3AF37",
  "Team Mexican Pink": "#E4007C",
  "Team Middle Yellow Red": "#ECB176",
  "Team Mikado Yellow": "#FFC40C",
  "Team Mimi Pink": "#FFDAE9",
  "Team Minion Yellow": "#F5E050",
  "Team Mint Cream": "#F5FFFA",
  "Team Mint Green": "#98FF98",
  "Team Misty Rose": "#FFE4E1",
  "Team Nadeshiko Pink": "#F6ADC6",
  "Team Naples Yellow": "#FADA5E",
  "Team Navajo White": "#FFDEAD",
  "Team Neon Blue": "#4666FF",
  "Team Neon Carrot": "#FFA343",
  "Team Neon Green": "#39FF14",
  "Team New York Pink": "#D7837F",
  "Team Old Gold": "#CFB53B",
  "Team Orange Peel": "#FF9F00",
  "Team Orange Soda": "#FA5B3D",
  "Team Orchid Pink": "#F2BDCD",
  "Team Outrageous Orange": "#FF6E4A",
  "Team Pale Aqua": "#BCD4E6",
  "Team Pale Cerulean": "#9BC4E2",
  "Team Pale Pink": "#FADADD",
  "Team Pale Spring Bud": "#ECEBBD",
  "Team Papaya Whip": "#FFEFD5",
  "Team Paradise Pink": "#E63E62",
  "Team Pastel Pink": "#DEA5A4",
  "Team Peach Puff": "#FFDAB9",
  "Team Permanent Geranium Lake": "#E12C2C",
  "Team Persian Orange": "#D99058",
  "Team Persian Pink": "#F77FBE",
  "Team Persian Red": "#CC3333",
  "Team Persian Rose": "#FE28A2",
  "Team Pink Flamingo": "#FC74FD",
  "Team Pink Lace": "#FFDDF4",
  "Team Pink Lavender": "#D8B2D1",
  "Team Pink Sherbet": "#F78FA7",
  "Team Portland Orange": "#FF5A36",
  "Team Powder Blue": "#B0E0E6",
  "Team Princeton Orange": "#F58025",
  "Team Psychedelic Purple": "#DF00FF",
  "Team Purple Pizzazz": "#FE4EDA",
  "Team Queen Pink": "#E8CCD7",
  "Team Radical Red": "#FF355E",
  "Team Raw Sienna": "#D68A59",
  "Team Razzle Dazzle Rose": "#FF33CC",
  "Team Red Salsa": "#FD3A4A",
  "Team Robin Egg Blue": "#00CCCC",
  "Team Rose Bonbon": "#F9429E",
  "Team Rose Madder": "#E32636",
  "Team Rose Pink": "#FF66CC",
  "Team Rosso Corsa": "#D40000",
  "Team Royal Yellow": "#FADA5E",
  "Team Rubine Red": "#D10056",
  "Team Safety Orange": "#FF7800",
  "Team Safety Yellow": "#EED202",
  "Team Salmon Pink": "#FF91A4",
  "Team Sandy Brown": "#F4A460",
  "Team Satin Sheen Gold": "#CBA135",
  "Team Schauss Pink": "#FF91AF",
  "Team School Bus Yellow": "#FFD800",
  "Team Selective Yellow": "#FFBA00",
  "Team Sheen Green": "#8FD400",
  "Team Shimmering Blush": "#D98695",
  "Team Shocking Pink": "#FC0FC0",
  "Team Sizzling Red": "#FF3855",
  "Team Sizzling Sunrise": "#FFDB00",
  "Team Sky Blue": "#87CEEB",
  "Team Sky Magenta": "#CF71AF",
  "Team Slate Blue": "#6A5ACD",
  "Team Spanish Carmine": "#D10047",
  "Team Spanish Orange": "#E86100",
  "Team Spanish Pink": "#F7BFBE",
  "Team Spanish Red": "#E60026",
  "Team Spanish Sky Blue": "#00FFFF",
  "Team Spring Bud": "#A7FC00",
  "Team Spring Frost": "#87FF2A",
  "Team Spring Green": "#00FF7F",
  "Team Steel Pink": "#CC33CC",
  "Team Stil De Grain Yellow": "#FADA5E",
  "Team Super Pink": "#CF6BA9",
  "Team Tango Pink": "#E4717A",
  "Team Tart Orange": "#FB4D46",
  "Team Tea Green": "#D0F0C0",
  "Team Tea Rose": "#F88379",
  "Team Terra Cotta": "#E2725B",
  "Team Thulian Pink": "#DE6FA1",
  "Team Tickle Me Pink": "#FC89AC",
  "Team Titanium Yellow": "#EEE600",
  "Team True Blue": "#2D68C4",
  "Team Tufts Blue": "#3E8EDE",
  "Team Turquoise Blue": "#00FFEF",
  "Team Turquoise Green": "#A0D6B4",
  "Team Ultra Pink": "#FF6FFF",
  "Team Ultra Red": "#FC6C85",
  "Team Ultramarine Blue": "#4166F5",
  "Team Unbleached Silk": "#FFDDCA",
  "Team United Nations Blue": "#5B92E5",
  "Team Unmellow Yellow": "#FFFF66",
  "Team Uranian Blue": "#AFDBF5",
  "Team Vanilla Ice": "#F38FA9",
  "Team Vivid Sky Blue": "#00CCFF",
  "Team Vivid Tangerine": "#FFA089",
  "Team Vivid Violet": "#9F00FF",
  "Team Wild Blue Yonder": "#A2ADD0",
  "Team Wild Orchid": "#D470A2",
  "Team Wild Strawberry": "#FF43A4",
  "Team Wild Watermelon": "#FC6C85",
  "Team Winter Sky": "#FF007C",
  "Team Yellow Orange": "#FFAE42",
  "Team Yellow Sunshine": "#FFF700",
};



// export default { HarryPotter, Twilight, Colors };
export default { Colors };
